#!/bin/bash
# Auto-generate .env file from environment variables
# Usage: ENVIRONMENT=dev DB_PASS=xxx API_KEY=xxx ./setup-env.sh

set -e

# Required parameters
ENVIRONMENT=${ENVIRONMENT:-prod}
DB_PASS=${DB_PASS:?ERROR: DB_PASS is required}
API_KEY_LIST=${API_KEY_LIST:-}

# Database settings
DB_USER="guangfu"
DB_HOST="postgres"
DB_PORT="5432"
DB_NAME="guangfu"
DATABASE_URL="postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}"

TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")

# Create .env file
cat > .env <<EOF
# ============================================================================
# Environment Variables (Auto-generated by CI/CD)
# ============================================================================
# Generated at: ${TIMESTAMP}
# Environment: ${ENVIRONMENT}
# DO NOT EDIT MANUALLY - Changes will be overwritten on next deployment
# ============================================================================

# ----------------------------------------------------------------------------
# Application Settings
# ----------------------------------------------------------------------------
ENVIRONMENT=${ENVIRONMENT}
APP_TITLE=花蓮光復救災平台 API
PORT=8080

# API Keys (from secrets)
ALLOW_MODIFY_API_KEY_LIST=${API_KEY_LIST}

# Server URLs
PROD_SERVER_URL=https://api.gf250923.org
DEV_SERVER_URL=https://uat-api.gf250923.org

# ----------------------------------------------------------------------------
# Database Settings (PostgreSQL)
# ----------------------------------------------------------------------------
POSTGRES_USER=${DB_USER}
POSTGRES_PASSWORD=${DB_PASS}
POSTGRES_DB=${DB_NAME}

DB_USER=${DB_USER}
DB_PASS=${DB_PASS}
DB_NAME=${DB_NAME}

# Database connection URL (auto-generated)
DATABASE_URL=${DATABASE_URL}
EOF

# Verify .env file was created
if [ ! -s .env ]; then
  echo "ERROR: .env file is empty or was not created"
  exit 1
fi

echo "✓ Environment file created for ${ENVIRONMENT}"
echo "✓ File size: $(wc -c < .env) bytes"
echo "✓ Non-comment lines: $(grep -c '^[^#]' .env || echo 0)"
