#!/bin/bash
# Auto-generate .env file from environment variables
# Usage:
#   ENVIRONMENT=dev DB_PASS=xxx API_KEY_LIST=key1,key2 \
#   LINE_CLIENT_ID=your_line_client_id \
#   LINE_CLIENT_SECRET=your_line_client_secret \
#   ./setup-env.sh
#
# Note: LINE_REDIRECT_URI 會根據 ENVIRONMENT 自動生成，通常不需要手動設定

set -e

# Required parameters
ENVIRONMENT=${ENVIRONMENT:-prod}
DB_PASS=${DB_PASS:?ERROR: DB_PASS is required}
API_KEY_LIST=${API_KEY_LIST:-}

# Line Login parameters
LINE_CLIENT_ID=${LINE_CLIENT_ID:-""}
LINE_CLIENT_SECRET=${LINE_CLIENT_SECRET:-""}

# LINE_REDIRECT_URI 根據環境自動生成（不是 secret，可以公開）
# 可透過環境變數覆寫以支援特殊情況
if [ -z "$LINE_REDIRECT_URI" ]; then
  if [ "$ENVIRONMENT" = "prod" ]; then
    LINE_REDIRECT_URI="https://api.gf250923.org/line/callback"
  elif [ "$ENVIRONMENT" = "dev" ]; then
    LINE_REDIRECT_URI="https://uat-api.gf250923.org/line/callback"
  else
    LINE_REDIRECT_URI="http://localhost:8080/line/callback"
  fi
fi

# Database settings
DB_USER="guangfu"
DB_HOST="postgres"
DB_PORT="5432"
DB_NAME="guangfu"
DATABASE_URL="postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}"

TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")

# Create .env file
cat > .env <<EOF
# ============================================================================
# Environment Variables (Auto-generated by CI/CD)
# ============================================================================
# Generated at: ${TIMESTAMP}
# Environment: ${ENVIRONMENT}
# DO NOT EDIT MANUALLY - Changes will be overwritten on next deployment
# ============================================================================

# ----------------------------------------------------------------------------
# Application Settings
# ----------------------------------------------------------------------------
ENVIRONMENT=${ENVIRONMENT}
APP_TITLE=花蓮光復救災平台 API
PORT=8080

# API Keys (from secrets)
ALLOW_MODIFY_API_KEY_LIST=${API_KEY_LIST}

# Server URLs
PROD_SERVER_URL=https://api.gf250923.org
DEV_SERVER_URL=https://uat-api.gf250923.org

# ----------------------------------------------------------------------------
# Database Settings (PostgreSQL)
# ----------------------------------------------------------------------------
POSTGRES_USER=${DB_USER}
POSTGRES_PASSWORD=${DB_PASS}
POSTGRES_DB=${DB_NAME}

DB_USER=${DB_USER}
DB_PASS=${DB_PASS}
DB_NAME=${DB_NAME}

# Database connection URL (auto-generated)
DATABASE_URL=${DATABASE_URL}

# ----------------------------------------------------------------------------
# LINE Login Settings
# ----------------------------------------------------------------------------
# LINE_REDIRECT_URI is auto-generated based on ENVIRONMENT
LINE_CLIENT_ID=${LINE_CLIENT_ID}
LINE_CLIENT_SECRET=${LINE_CLIENT_SECRET}
LINE_REDIRECT_URI=${LINE_REDIRECT_URI}
EOF

# Verify .env file was created
if [ ! -s .env ]; then
  echo "ERROR: .env file is empty or was not created"
  exit 1
fi

echo "✓ Environment file created for ${ENVIRONMENT}"
echo "✓ File size: $(wc -c < .env) bytes"
echo "✓ Non-comment lines: $(grep -c '^[^#]' .env || echo 0)"
