"""add_spam_warn_to_supplies

Revision ID: 379340d63c90
Revises: 0f01908e6629
Create Date: 2025-10-09 23:11:11.345408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '379340d63c90'
down_revision: Union[str, Sequence[str], None] = '0f01908e6629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplies', sa.Column('spam_warn', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplies', 'spam_warn')
    # ### end Alembic commands ###
